# Generated by Django 3.2 on 2021-04-23 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0002_searchfield'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchField',
        ),
    ]
